version: '3'

services:
  elasticsearch:
    image: midaug/elasticsearch:7.1.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
    networks:
      - elk

  kibana:
    image: midaug/kibana:7.1.1
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601" 
    depends_on:
      - elasticsearch
    networks:
      - elk



networks:
  elk:
    driver: bridge