name: docker_build_push

on:
  workflow_dispatch:
    inputs:
      tag:   
        required: true
      elk_version:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push elasticsearch
        uses: docker/build-push-action@v2
        with:
          context: ./elasticsearch
          platforms: linux/amd64,linux/arm64
          push: true
          tags: midaug/elasticsearch:latest,midaug/elasticsearch:${{ github.event.inputs.tag }}
      - name: Build and push kibana
        uses: docker/build-push-action@v2
        with:
          context: ./kibana
          platforms: linux/amd64,linux/arm64
          push: true
          tags: midaug/kibana:latest,midaug/kibana:${{ github.event.inputs.tag }}
      - name: Build and push logstash
        uses: docker/build-push-action@v2
        with:
          context: ./logstash
          platforms: linux/amd64,linux/arm64
          push: true
          tags: midaug/logstash:latest,midaug/logstash:${{ github.event.inputs.tag }}                    
